title: SPAGRM
description: A tutorial on how to use SPAGRM.
theme: just-the-docs

baseurl: SPAGRM.github.io/
url: https://fantasy-xuhe.github.io/
github_username:  Fantasy-XuHe

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

html_theme = 'sphinx_book_theme'

html_theme_options = {
    "show_navbar_depth": 2
}
